runtime: nodejs20
service: venu-api
instance_class: F2

env_variables:
  DATABASE_CLIENT: 'postgres'
  DATABASE_HOST: '34.128.117.0'
  DATABASE_PORT: '5432'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'root'
  INSTANCE_CONNECTION_NAME: 'venu-project-408000:asia-southeast2:postgres'

beta_settings:
  cloud_sql_instances: 'venu-project-408000:asia-southeast2:postgres'
